{"data": {"repository": {"pullRequest": {"id": "MDExOlB1bGxSZXF1ZXN0NTA4ODI4ODQ2", "number": 9279, "title": "CB-9449 if AWS returns that DBInstance does not exsist, then we shall\u2026", "bodyText": "\u2026 consider this as the termination protection is not enabled.\nBefore this change if somebody went to AWS console and removed the protection and deleted the DB instance, that caused Environment/SDX/DH delete failures, since Redbeams would just thorw a CloudConnectorException for delete call and Environment/SDX/DH deletion stuck forever. After this change Redbeams realises that DB does not exsist anymore and it just proceeds and Environment/SDX/DH deletion will be successful.\nI have intentionally changed the unit test as well, to make sure that it reflects the the expected behaviour.\nSee detailed description in the commit message.", "createdAt": "2020-10-23T09:12:12Z", "url": "https://github.com/hortonworks/cloudbreak/pull/9279", "merged": true, "mergeCommit": {"oid": "cface9a247967109ff05d7400c9087e21390d06d"}, "closed": true, "closedAt": "2020-10-27T06:57:10Z", "author": {"login": "akanto"}, "timelineItems": {"totalCount": 7, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpPPAAABdVS9J6ABqjM5MTI5NjA5MjE=", "endCursor": "Y3Vyc29yOnYyOpPPAAABdWjYMEAFqTUxNzM5MjQ3Mw==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"__typename": "HeadRefForcePushedEvent", "beforeCommit": {"oid": "a837a36d1fb87beae11b8f932be3065e53da780a", "author": {"user": {"login": "akanto", "name": "Attila Kanto"}}, "url": "https://github.com/hortonworks/cloudbreak/commit/a837a36d1fb87beae11b8f932be3065e53da780a", "committedDate": "2020-10-23T09:11:21Z", "message": "CB-9449 if AWS returns that DBInstance does not exsist, then we shall consider this as the termination protection is not enabled.\n\nBefore this change if somebody went to AWS console and removed the protection and deleted the DB instance, that caused Environment/SDX/DH delete failures, since Redbeams would just thorw a CloudConnectorException for delete call and Environment/SDX/DH deletion stuck forever. After this change Redbeams realises that DB does not exsist anymore and it just proceeds and Environment/SDX/DH deletion will be successful.\n\nI have intentionally changed the unit test as well, to make sure that it reflects the the expected behaviour."}, "afterCommit": {"oid": "c4e94063f7ce8635bd399aa3158f7a63c6f24803", "author": {"user": {"login": "akanto", "name": "Attila Kanto"}}, "url": "https://github.com/hortonworks/cloudbreak/commit/c4e94063f7ce8635bd399aa3158f7a63c6f24803", "committedDate": "2020-10-23T09:14:25Z", "message": "CB-9449 if AWS returns that DBInstance does not exist, then we shall consider this as the termination protection is not enabled.\n\nBefore this change if somebody went to AWS console and removed the protection and deleted the DB instance, that caused Environment/SDX/DH delete failures, since Redbeams would just thorw a CloudConnectorException for delete call and Environment/SDX/DH deletion stuck forever. After this change Redbeams realises that DB does not exsist anymore and it just proceeds and Environment/SDX/DH deletion will be successful.\n\nI have intentionally changed the unit test as well, to make sure that it reflects the the expected behaviour."}}, {"__typename": "PullRequestReview", "id": "MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NTE2NTc1NDM1", "url": "https://github.com/hortonworks/cloudbreak/pull/9279#pullrequestreview-516575435", "createdAt": "2020-10-26T09:01:36Z", "commit": {"oid": "c4e94063f7ce8635bd399aa3158f7a63c6f24803"}, "state": "CHANGES_REQUESTED", "comments": {"totalCount": 2, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0xMC0yNlQwOTowMTozNlrOHoGHSg==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0xMC0yNlQxMToxODoxNlrOHoLCxw==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUxMTgwNTI1OA==", "bodyText": "Typo: exists => exist\n\n\nPossible typo: therefor is a legit word, however after looking it up I found it has a different meaning: for it, for that.\nhttps://www.grammarly.com/blog/therefore-vs-therefor/\n\n\nI THINK therefore would be better here.", "url": "https://github.com/hortonworks/cloudbreak/pull/9279#discussion_r511805258", "createdAt": "2020-10-26T09:01:36Z", "author": {"login": "gergopapi2"}, "path": "cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsStatusLookupService.java", "diffHunk": "@@ -61,6 +62,9 @@ public boolean isDeleteProtectionEnabled(AuthenticatedContext ac, DatabaseStack\n         try {\n             LOGGER.debug(\"RDS Checking if delete protection is enabled\");\n             describeDBInstancesResult = rdsClient.describeDBInstances(describeDBInstancesRequest);\n+        } catch (DBInstanceNotFoundException ex) {\n+            LOGGER.debug(\"DB Instance does not exists! Therefor termination protection check is not relevant anymore: {}\", ex.getMessage());", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "c4e94063f7ce8635bd399aa3158f7a63c6f24803"}, "originalPosition": 13}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUxMTg4NjAyMw==", "bodyText": "typo: exists => exist", "url": "https://github.com/hortonworks/cloudbreak/pull/9279#discussion_r511886023", "createdAt": "2020-10-26T11:18:16Z", "author": {"login": "gergopapi2"}, "path": "cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsStatusLookupService.java", "diffHunk": "@@ -37,6 +37,7 @@ public ExternalDatabaseStatus getStatus(AuthenticatedContext ac, DatabaseStack d\n         try {\n             describeDBInstancesResult = rdsClient.describeDBInstances(describeDBInstancesRequest);\n         } catch (DBInstanceNotFoundException ex) {\n+            LOGGER.debug(\"DB Instance does not exists: {}\", ex.getMessage());", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "c4e94063f7ce8635bd399aa3158f7a63c6f24803"}, "originalPosition": 4}]}}, {"__typename": "HeadRefForcePushedEvent", "beforeCommit": {"oid": "c4e94063f7ce8635bd399aa3158f7a63c6f24803", "author": {"user": {"login": "akanto", "name": "Attila Kanto"}}, "url": "https://github.com/hortonworks/cloudbreak/commit/c4e94063f7ce8635bd399aa3158f7a63c6f24803", "committedDate": "2020-10-23T09:14:25Z", "message": "CB-9449 if AWS returns that DBInstance does not exist, then we shall consider this as the termination protection is not enabled.\n\nBefore this change if somebody went to AWS console and removed the protection and deleted the DB instance, that caused Environment/SDX/DH delete failures, since Redbeams would just thorw a CloudConnectorException for delete call and Environment/SDX/DH deletion stuck forever. After this change Redbeams realises that DB does not exsist anymore and it just proceeds and Environment/SDX/DH deletion will be successful.\n\nI have intentionally changed the unit test as well, to make sure that it reflects the the expected behaviour."}, "afterCommit": {"oid": "57b1cfedac7d1e13959d3dcffa74c959f8716037", "author": {"user": {"login": "akanto", "name": "Attila Kanto"}}, "url": "https://github.com/hortonworks/cloudbreak/commit/57b1cfedac7d1e13959d3dcffa74c959f8716037", "committedDate": "2020-10-26T11:54:48Z", "message": "CB-9449 if AWS returns that DBInstance does not exist, then we shall consider this as the termination protection is not enabled.\n\nBefore this change if somebody went to AWS console and removed the protection and deleted the DB instance, that caused Environment/SDX/DH delete failures, since Redbeams would just thorw a CloudConnectorException for delete call and Environment/SDX/DH deletion stuck forever. After this change Redbeams realises that DB does not exsist anymore and it just proceeds and Environment/SDX/DH deletion will be successful.\n\nI have intentionally changed the unit test as well, to make sure that it reflects the the expected behaviour."}}, {"__typename": "HeadRefForcePushedEvent", "beforeCommit": {"oid": "57b1cfedac7d1e13959d3dcffa74c959f8716037", "author": {"user": {"login": "akanto", "name": "Attila Kanto"}}, "url": "https://github.com/hortonworks/cloudbreak/commit/57b1cfedac7d1e13959d3dcffa74c959f8716037", "committedDate": "2020-10-26T11:54:48Z", "message": "CB-9449 if AWS returns that DBInstance does not exist, then we shall consider this as the termination protection is not enabled.\n\nBefore this change if somebody went to AWS console and removed the protection and deleted the DB instance, that caused Environment/SDX/DH delete failures, since Redbeams would just thorw a CloudConnectorException for delete call and Environment/SDX/DH deletion stuck forever. After this change Redbeams realises that DB does not exsist anymore and it just proceeds and Environment/SDX/DH deletion will be successful.\n\nI have intentionally changed the unit test as well, to make sure that it reflects the the expected behaviour."}, "afterCommit": {"oid": "9629f800006a95f4ffa71305ed31379e49be1143", "author": {"user": {"login": "akanto", "name": "Attila Kanto"}}, "url": "https://github.com/hortonworks/cloudbreak/commit/9629f800006a95f4ffa71305ed31379e49be1143", "committedDate": "2020-10-26T13:05:08Z", "message": "CB-9449 if AWS returns that DBInstance does not exist, then we shall consider this as the termination protection is not enabled.\n\nBefore this change if somebody went to AWS console and removed the protection and deleted the DB instance, that caused Environment/SDX/DH delete failures, since Redbeams would just throw a CloudConnectorException for delete call and Environment/SDX/DH deletion stuck forever. After this change Redbeams realises that DB does not exist anymore and it just proceeds and Environment/SDX/DH deletion will be successful.\n\nI have intentionally changed the unit test as well, to make sure that it reflects the the expected behaviour."}}, {"__typename": "PullRequestCommit", "commit": {"oid": "7f6e3ab33ca8bb8cf2203802b851dff346220c93", "author": {"user": {"login": "akanto", "name": "Attila Kanto"}}, "url": "https://github.com/hortonworks/cloudbreak/commit/7f6e3ab33ca8bb8cf2203802b851dff346220c93", "committedDate": "2020-10-26T13:05:44Z", "message": "CB-9449 if AWS returns that DBInstance does not exist, then we shall consider this as the termination protection is not enabled.\n\nBefore this change if somebody went to AWS console and removed the protection and deleted the DB instance, that caused Environment/SDX/DH delete failures, since Redbeams would just throw a CloudConnectorException for delete call and Environment/SDX/DH deletion stuck forever. After this change Redbeams realises that DB does not exist anymore and it just proceeds and Environment/SDX/DH deletion will be successful.\n\nI have intentionally changed the unit test as well, to make sure that it reflects the the expected behaviour."}}, {"__typename": "HeadRefForcePushedEvent", "beforeCommit": {"oid": "9629f800006a95f4ffa71305ed31379e49be1143", "author": {"user": {"login": "akanto", "name": "Attila Kanto"}}, "url": "https://github.com/hortonworks/cloudbreak/commit/9629f800006a95f4ffa71305ed31379e49be1143", "committedDate": "2020-10-26T13:05:08Z", "message": "CB-9449 if AWS returns that DBInstance does not exist, then we shall consider this as the termination protection is not enabled.\n\nBefore this change if somebody went to AWS console and removed the protection and deleted the DB instance, that caused Environment/SDX/DH delete failures, since Redbeams would just throw a CloudConnectorException for delete call and Environment/SDX/DH deletion stuck forever. After this change Redbeams realises that DB does not exist anymore and it just proceeds and Environment/SDX/DH deletion will be successful.\n\nI have intentionally changed the unit test as well, to make sure that it reflects the the expected behaviour."}, "afterCommit": {"oid": "7f6e3ab33ca8bb8cf2203802b851dff346220c93", "author": {"user": {"login": "akanto", "name": "Attila Kanto"}}, "url": "https://github.com/hortonworks/cloudbreak/commit/7f6e3ab33ca8bb8cf2203802b851dff346220c93", "committedDate": "2020-10-26T13:05:44Z", "message": "CB-9449 if AWS returns that DBInstance does not exist, then we shall consider this as the termination protection is not enabled.\n\nBefore this change if somebody went to AWS console and removed the protection and deleted the DB instance, that caused Environment/SDX/DH delete failures, since Redbeams would just throw a CloudConnectorException for delete call and Environment/SDX/DH deletion stuck forever. After this change Redbeams realises that DB does not exist anymore and it just proceeds and Environment/SDX/DH deletion will be successful.\n\nI have intentionally changed the unit test as well, to make sure that it reflects the the expected behaviour."}}, {"__typename": "PullRequestReview", "id": "MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NTE3MzkyNDcz", "url": "https://github.com/hortonworks/cloudbreak/pull/9279#pullrequestreview-517392473", "createdAt": "2020-10-27T06:56:40Z", "commit": {"oid": "7f6e3ab33ca8bb8cf2203802b851dff346220c93"}, "state": "APPROVED", "comments": {"totalCount": 0, "pageInfo": {"startCursor": null, "endCursor": null, "hasNextPage": false, "hasPreviousPage": false}, "nodes": []}}]}}}, "rateLimit": {"limit": 5000, "remaining": 2054, "cost": 1, "resetAt": "2021-11-01T14:51:55Z"}}}