{"data": {"repository": {"pullRequest": {"id": "MDExOlB1bGxSZXF1ZXN0NDQ3ODQwMjU1", "number": 4941, "title": "Issue 4940: Propagating Transaction Exceptions to the caller", "bodyText": "Change log description\nRaises and handles TxnFailedException instead of RuntimeException on Txn operations\nPurpose of the change\nFixes #4940\nWhat the code does\nThe TransactionalEventStreamWriter throws both TxnFailedException and RuntimeException. The latter is used in a mixed manner where the former is exclusively defined for the purpose of the TransactionalEventStreamWriter. This puts the client in a dilemma when using syntax like the following:\n        Retry.withExpBackoff(DELAY, MULTIPLIER, ATTEMPTS, MAXDELAY)\n             .retryingOn(TxnFailedException.class)\n             .throwingOn(RuntimeException.class)\n             .run(() -> {stateHelper.afterWrite(); return true;});\n\nbecause it has to be selectively thrown on a case by case basis.\nThis change makes the Exception raised consistent across io.pravega.client.stream txn operations.\nHow to verify it\nAll unit-tests, integration tests and system tests", "createdAt": "2020-07-12T02:06:49Z", "url": "https://github.com/pravega/pravega/pull/4941", "merged": true, "mergeCommit": {"oid": "6ad4dfe3589428bda7665bdd2d97a2af061c8c8b"}, "closed": true, "closedAt": "2020-07-16T19:19:41Z", "author": {"login": "ravibeta"}, "timelineItems": {"totalCount": 15, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpPPAAABc0DC-3gH2gAyNDQ3ODQwMjU1OjY4ZGFhODI5YTY1MmYyNGQ3NmE0YjM0ZDMwODc5ZGM4NmQyY2EwMzQ=", "endCursor": "Y3Vyc29yOnYyOpPPAAABc1kQkggFqTQ1MDE0NDYxNQ==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"__typename": "PullRequestCommit", "commit": {"oid": "68daa829a652f24d76a4b34d30879dc86d2ca034", "author": {"user": {"login": "ravibeta", "name": "Ravi Rajamani"}}, "url": "https://github.com/pravega/pravega/commit/68daa829a652f24d76a4b34d30879dc86d2ca034", "committedDate": "2020-07-12T02:03:07Z", "message": "throws TxnFailedException\n\nSigned-off-by: Ravi Rajamani <ravi.rajamani@emc.com>"}}, {"__typename": "PullRequestCommit", "commit": {"oid": "664e756ebd2f79ba9ab3d0cb3815a0061d3713fa", "author": {"user": {"login": "ravibeta", "name": "Ravi Rajamani"}}, "url": "https://github.com/pravega/pravega/commit/664e756ebd2f79ba9ab3d0cb3815a0061d3713fa", "committedDate": "2020-07-12T02:51:11Z", "message": ":test:integration:checkstyleMain\n\nSigned-off-by: Ravi Rajamani <ravi.rajamani@emc.com>"}}, {"__typename": "PullRequestReview", "id": "MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDQ2ODQ5Nzk1", "url": "https://github.com/pravega/pravega/pull/4941#pullrequestreview-446849795", "createdAt": "2020-07-12T06:25:26Z", "commit": {"oid": "664e756ebd2f79ba9ab3d0cb3815a0061d3713fa"}, "state": "CHANGES_REQUESTED", "comments": {"totalCount": 7, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wNy0xMlQwNjoyNjoyMVrOGwRrdA==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wNy0xMlQwNjozMDo1NVrOGwRs-w==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1MzI3NDQ4NA==", "bodyText": "This comment does not add value. Can you please explain in which case, as an example, this method will throw this exception?", "url": "https://github.com/pravega/pravega/pull/4941#discussion_r453274484", "createdAt": "2020-07-12T06:26:21Z", "author": {"login": "eolivelli"}, "path": "client/src/main/java/io/pravega/client/stream/Transaction.java", "diffHunk": "@@ -92,13 +92,16 @@\n \n     /**\n      * Drops the transaction, causing all events written to it to be deleted.\n+     *\n+     * @throws TxnFailedException Error aborting transaction: FAILURE\n      */\n-    void abort();\n+    void abort() throws TxnFailedException;\n \n     /**\n      * Gets the status of the transaction.\n      *\n+     *  @throws TxnFailedException This exception could be thrown on checkStatus", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "664e756ebd2f79ba9ab3d0cb3815a0061d3713fa"}, "originalPosition": 13}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1MzI3NDUzNw==", "bodyText": "This is weird from the user point of view.\nTxnFailedException sounds like the transaction is broken or you broke it by calling this method.\nHere I would expect some new TxNotValidException", "url": "https://github.com/pravega/pravega/pull/4941#discussion_r453274537", "createdAt": "2020-07-12T06:26:58Z", "author": {"login": "eolivelli"}, "path": "client/src/main/java/io/pravega/client/stream/Transaction.java", "diffHunk": "@@ -92,13 +92,16 @@\n \n     /**\n      * Drops the transaction, causing all events written to it to be deleted.\n+     *\n+     * @throws TxnFailedException Error aborting transaction: FAILURE\n      */\n-    void abort();\n+    void abort() throws TxnFailedException;\n \n     /**\n      * Gets the status of the transaction.\n      *\n+     *  @throws TxnFailedException This exception could be thrown on checkStatus\n      *  @return Current status of the transaction\n      */\n-    Status checkStatus();\n+    Status checkStatus() throws TxnFailedException;", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "664e756ebd2f79ba9ab3d0cb3815a0061d3713fa"}, "originalPosition": 17}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1MzI3NDU3Mw==", "bodyText": "This kind of comments are not useful to the user", "url": "https://github.com/pravega/pravega/pull/4941#discussion_r453274573", "createdAt": "2020-07-12T06:27:32Z", "author": {"login": "eolivelli"}, "path": "client/src/main/java/io/pravega/client/stream/TransactionalEventStreamWriter.java", "diffHunk": "@@ -26,17 +26,19 @@\n      * Start a new transaction on this stream. This allows events written to the transaction be written an committed atomically.\n      * Note that transactions can only be open for {@link EventWriterConfig#transactionTimeoutTime}.\n      * \n+     * @throws TxnFailedException This exception could be thrown on beginTxn", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "664e756ebd2f79ba9ab3d0cb3815a0061d3713fa"}, "originalPosition": 4}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1MzI3NDY2Nw==", "bodyText": "How can a transaction that does not exist can fail?\nMaybe it is fine to have this error here but it deserves a little explanation in javadocs", "url": "https://github.com/pravega/pravega/pull/4941#discussion_r453274667", "createdAt": "2020-07-12T06:28:42Z", "author": {"login": "eolivelli"}, "path": "client/src/main/java/io/pravega/client/stream/TransactionalEventStreamWriter.java", "diffHunk": "@@ -26,17 +26,19 @@\n      * Start a new transaction on this stream. This allows events written to the transaction be written an committed atomically.\n      * Note that transactions can only be open for {@link EventWriterConfig#transactionTimeoutTime}.\n      * \n+     * @throws TxnFailedException This exception could be thrown on beginTxn\n      * @return A transaction through which multiple events can be written atomically.\n      */\n-    Transaction<Type> beginTxn();\n+    Transaction<Type> beginTxn() throws TxnFailedException;", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "664e756ebd2f79ba9ab3d0cb3815a0061d3713fa"}, "originalPosition": 8}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1MzI3NDc2Ng==", "bodyText": "Methods that return a CP should not throw but return a failed CompletableFuture", "url": "https://github.com/pravega/pravega/pull/4941#discussion_r453274766", "createdAt": "2020-07-12T06:30:01Z", "author": {"login": "eolivelli"}, "path": "test/integration/src/main/java/io/pravega/test/integration/selftest/Actor.java", "diffHunk": "@@ -81,10 +82,18 @@ protected void doStart() {\n         notifyStarted();\n         this.runTask = Futures\n                 .delayedFuture(INITIAL_DELAY, this.executorService)\n-                .thenCompose(v -> run());\n+                .thenCompose(v -> runWithException());\n         this.runTask.whenComplete((r, ex) -> stopAsync());\n     }\n \n+    private CompletableFuture<Void> runWithException() {\n+        try {\n+            return run();\n+        } catch (TxnFailedException ex) {\n+            throw new RuntimeException(ex);", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "664e756ebd2f79ba9ab3d0cb3815a0061d3713fa"}, "originalPosition": 21}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1MzI3NDgxMg==", "bodyText": "The same here", "url": "https://github.com/pravega/pravega/pull/4941#discussion_r453274812", "createdAt": "2020-07-12T06:30:21Z", "author": {"login": "eolivelli"}, "path": "test/integration/src/main/java/io/pravega/test/integration/selftest/Actor.java", "diffHunk": "@@ -119,7 +128,7 @@ protected void doStop() {\n     /**\n      * Executes the role of this Actor.\n      */\n-    protected abstract CompletableFuture<Void> run();\n+    protected abstract CompletableFuture<Void> run() throws TxnFailedException;", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "664e756ebd2f79ba9ab3d0cb3815a0061d3713fa"}, "originalPosition": 33}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1MzI3NDg3NQ==", "bodyText": "return a failed future  here and in other points", "url": "https://github.com/pravega/pravega/pull/4941#discussion_r453274875", "createdAt": "2020-07-12T06:30:55Z", "author": {"login": "eolivelli"}, "path": "test/integration/src/main/java/io/pravega/test/integration/selftest/StreamProducerDataSource.java", "diffHunk": "@@ -258,5 +261,13 @@ private void postStreamDeletion(String name) {\n         this.state.recordDeletedStream(name);\n     }\n \n+    private CompletableFuture<Void> deleteStreamThrowing(String name, Duration timeout) {\n+        try {\n+            return this.store.deleteStream(name, this.config.getTimeout());\n+        } catch (TxnFailedException ex) {\n+            throw new CompletionException(ex);", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "664e756ebd2f79ba9ab3d0cb3815a0061d3713fa"}, "originalPosition": 33}]}}, {"__typename": "PullRequestCommit", "commit": {"oid": "22b4ebe8fbee8c92bf0c0dcc72d19780a489b4a8", "author": {"user": {"login": "ravibeta", "name": "Ravi Rajamani"}}, "url": "https://github.com/pravega/pravega/commit/22b4ebe8fbee8c92bf0c0dcc72d19780a489b4a8", "committedDate": "2020-07-13T23:29:57Z", "message": "throws TxnFailedException\n\nSigned-off-by: Ravi Rajamani <ravi.rajamani@emc.com>"}}, {"__typename": "PullRequestReview", "id": "MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDQ3Njg1ODgx", "url": "https://github.com/pravega/pravega/pull/4941#pullrequestreview-447685881", "createdAt": "2020-07-13T23:37:45Z", "commit": {"oid": "22b4ebe8fbee8c92bf0c0dcc72d19780a489b4a8"}, "state": "CHANGES_REQUESTED", "comments": {"totalCount": 0, "pageInfo": {"startCursor": null, "endCursor": null, "hasNextPage": false, "hasPreviousPage": false}, "nodes": []}}, {"__typename": "PullRequestReview", "id": "MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDQ3NjkyODQ2", "url": "https://github.com/pravega/pravega/pull/4941#pullrequestreview-447692846", "createdAt": "2020-07-13T23:57:48Z", "commit": {"oid": "22b4ebe8fbee8c92bf0c0dcc72d19780a489b4a8"}, "state": "CHANGES_REQUESTED", "comments": {"totalCount": 6, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wNy0xM1QyMzo1Nzo0OFrOGw-8Ww==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wNy0xNFQwMDowMzoyN1rOGw_C-Q==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1NDAxNjA5MQ==", "bodyText": "This is a bit confusing. If failing the transaction fails it throws TxnFailedException but this is exactly the opposite of what happened. If the transaction has failed then this should return successfully.", "url": "https://github.com/pravega/pravega/pull/4941#discussion_r454016091", "createdAt": "2020-07-13T23:57:48Z", "author": {"login": "tkaitchuck"}, "path": "client/src/main/java/io/pravega/client/stream/Transaction.java", "diffHunk": "@@ -92,13 +92,16 @@\n \n     /**\n      * Drops the transaction, causing all events written to it to be deleted.\n+     *\n+     * @throws TxnFailedException Error aborting transaction: FAILURE", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "22b4ebe8fbee8c92bf0c0dcc72d19780a489b4a8"}, "originalPosition": 5}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1NDAxNjM3MA==", "bodyText": "Yes Status includes aborted.", "url": "https://github.com/pravega/pravega/pull/4941#discussion_r454016370", "createdAt": "2020-07-13T23:58:48Z", "author": {"login": "tkaitchuck"}, "path": "client/src/main/java/io/pravega/client/stream/Transaction.java", "diffHunk": "@@ -92,13 +92,16 @@\n \n     /**\n      * Drops the transaction, causing all events written to it to be deleted.\n+     *\n+     * @throws TxnFailedException Error aborting transaction: FAILURE\n      */\n-    void abort();\n+    void abort() throws TxnFailedException;\n \n     /**\n      * Gets the status of the transaction.\n      *\n+     *  @throws TxnFailedException This exception could be thrown on checkStatus\n      *  @return Current status of the transaction\n      */\n-    Status checkStatus();\n+    Status checkStatus() throws TxnFailedException;", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1MzI3NDUzNw=="}, "originalCommit": {"oid": "664e756ebd2f79ba9ab3d0cb3815a0061d3713fa"}, "originalPosition": 17}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1NDAxNzIxOQ==", "bodyText": "I don't think we want this behavior.\nIt seems legitimate to me to do:\ngetTxn(id).checkStatus()\n\nIn this case I would expect the result to return whatever the status was even if it is not OPEN.\nIf the code doesn't work this way. we should open an issue.", "url": "https://github.com/pravega/pravega/pull/4941#discussion_r454017219", "createdAt": "2020-07-14T00:01:27Z", "author": {"login": "tkaitchuck"}, "path": "client/src/main/java/io/pravega/client/stream/TransactionalEventStreamWriter.java", "diffHunk": "@@ -26,17 +26,19 @@\n      * Start a new transaction on this stream. This allows events written to the transaction be written an committed atomically.\n      * Note that transactions can only be open for {@link EventWriterConfig#transactionTimeoutTime}.\n      * \n+     * @throws TxnFailedException The Transaction is no longer in state {@link Transaction.Status#OPEN}\n      * @return A transaction through which multiple events can be written atomically.\n      */\n-    Transaction<Type> beginTxn();\n+    Transaction<Type> beginTxn() throws TxnFailedException;\n \n     /**\n      * Returns a previously created transaction.\n      * \n      * @param transactionId The result retained from calling {@link Transaction#getTxnId()}\n+     * @throws TxnFailedException The Transaction is no longer in state {@link Transaction.Status#OPEN}", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "22b4ebe8fbee8c92bf0c0dcc72d19780a489b4a8"}, "originalPosition": 14}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1NDAxNzU0MA==", "bodyText": "I think what we really want if for the controller client to dictate the exception type.\nSo instead of converting this, I think we should instead call getThrowingException which will just pass up whatever the underlying error was.", "url": "https://github.com/pravega/pravega/pull/4941#discussion_r454017540", "createdAt": "2020-07-14T00:02:33Z", "author": {"login": "tkaitchuck"}, "path": "client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java", "diffHunk": "@@ -144,15 +144,15 @@ public void abort() {\n                         log.debug(\"Got exception while writing to transaction on abort: {}\", e.getMessage());\n                     }\n                 }\n-                getAndHandleExceptions(controller.abortTransaction(stream, txId), RuntimeException::new);\n+                getAndHandleExceptions(controller.abortTransaction(stream, txId), TxnFailedException::new);", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "22b4ebe8fbee8c92bf0c0dcc72d19780a489b4a8"}, "originalPosition": 14}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1NDAxNzYwNQ==", "bodyText": "Same here", "url": "https://github.com/pravega/pravega/pull/4941#discussion_r454017605", "createdAt": "2020-07-14T00:02:44Z", "author": {"login": "tkaitchuck"}, "path": "client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java", "diffHunk": "@@ -176,9 +176,9 @@ private void throwIfClosed() throws TxnFailedException {\n     }\n \n     @Override\n-    public Transaction<Type> beginTxn() {\n+    public Transaction<Type> beginTxn() throws TxnFailedException {\n         TxnSegments txnSegments = getAndHandleExceptions(controller.createTransaction(stream, config.getTransactionTimeoutTime()),\n-                RuntimeException::new);\n+                TxnFailedException::new);", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "22b4ebe8fbee8c92bf0c0dcc72d19780a489b4a8"}, "originalPosition": 36}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1NDAxNzc4NQ==", "bodyText": "same here", "url": "https://github.com/pravega/pravega/pull/4941#discussion_r454017785", "createdAt": "2020-07-14T00:03:27Z", "author": {"login": "tkaitchuck"}, "path": "client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java", "diffHunk": "@@ -198,16 +198,16 @@ private void throwIfClosed() throws TxnFailedException {\n     }\n \n     @Override\n-    public Transaction<Type> getTxn(UUID txId) {\n+    public Transaction<Type> getTxn(UUID txId) throws TxnFailedException {\n         // check if the transaction is open.\n-        Status status = getAndHandleExceptions(controller.checkTransactionStatus(stream, txId), RuntimeException::new);\n+        Status status = getAndHandleExceptions(controller.checkTransactionStatus(stream, txId), TxnFailedException::new);", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "22b4ebe8fbee8c92bf0c0dcc72d19780a489b4a8"}, "originalPosition": 48}]}}, {"__typename": "PullRequestCommit", "commit": {"oid": "abda6de53f8603a5cafbc02302666cc0f8f8f857", "author": {"user": {"login": "ravibeta", "name": "Ravi Rajamani"}}, "url": "https://github.com/pravega/pravega/commit/abda6de53f8603a5cafbc02302666cc0f8f8f857", "committedDate": "2020-07-14T01:02:06Z", "message": "fix test\n\nSigned-off-by: Ravi Rajamani <ravi.rajamani@emc.com>"}}, {"__typename": "PullRequestCommit", "commit": {"oid": "18a2edb23fbee090629552847463aaec92b24a0f", "author": {"user": {"login": "ravibeta", "name": "Ravi Rajamani"}}, "url": "https://github.com/pravega/pravega/commit/18a2edb23fbee090629552847463aaec92b24a0f", "committedDate": "2020-07-14T02:15:56Z", "message": "fix checkstyleMain\n\nSigned-off-by: Ravi Rajamani <ravi.rajamani@emc.com>"}}, {"__typename": "PullRequestCommit", "commit": {"oid": "55246e44d26633f364c90e9b50e46964acc6edfd", "author": {"user": {"login": "ravibeta", "name": "Ravi Rajamani"}}, "url": "https://github.com/pravega/pravega/commit/55246e44d26633f364c90e9b50e46964acc6edfd", "committedDate": "2020-07-14T16:53:28Z", "message": "no throw from Transaction.checkStatus\n\nSigned-off-by: Ravi Rajamani <ravi.rajamani@emc.com>"}}, {"__typename": "PullRequestCommit", "commit": {"oid": "b76cf007f27ad91c24dc9a1821dd1a96a5bd31fa", "author": {"user": {"login": "ravibeta", "name": "Ravi Rajamani"}}, "url": "https://github.com/pravega/pravega/commit/b76cf007f27ad91c24dc9a1821dd1a96a5bd31fa", "committedDate": "2020-07-15T15:22:01Z", "message": "Use Futures.getThrowingException instead of Futures.getAndHandleExceptions\n\nSigned-off-by: Ravi Rajamani <ravi.rajamani@emc.com>"}}, {"__typename": "PullRequestCommit", "commit": {"oid": "4681d7be0b518cf7d41f51d0e48afb60fd6c12ad", "author": {"user": {"login": "ravibeta", "name": "Ravi Rajamani"}}, "url": "https://github.com/pravega/pravega/commit/4681d7be0b518cf7d41f51d0e48afb60fd6c12ad", "committedDate": "2020-07-15T16:28:20Z", "message": "Merge branch 'master' into issue-4940-txnfailedexception"}}, {"__typename": "PullRequestCommit", "commit": {"oid": "7c8ee1458493fe05c04b0c60732f48d2c131d8b4", "author": {"user": {"login": "ravibeta", "name": "Ravi Rajamani"}}, "url": "https://github.com/pravega/pravega/commit/7c8ee1458493fe05c04b0c60732f48d2c131d8b4", "committedDate": "2020-07-15T17:12:55Z", "message": "propagate exceptions\n\nSigned-off-by: Ravi Rajamani <ravi.rajamani@emc.com>"}}, {"__typename": "PullRequestReview", "id": "MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDQ5MzMwODc5", "url": "https://github.com/pravega/pravega/pull/4941#pullrequestreview-449330879", "createdAt": "2020-07-15T21:06:51Z", "commit": {"oid": "7c8ee1458493fe05c04b0c60732f48d2c131d8b4"}, "state": "APPROVED", "comments": {"totalCount": 0, "pageInfo": {"startCursor": null, "endCursor": null, "hasNextPage": false, "hasPreviousPage": false}, "nodes": []}}, {"__typename": "PullRequestReview", "id": "MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDQ5NDg4NzM4", "url": "https://github.com/pravega/pravega/pull/4941#pullrequestreview-449488738", "createdAt": "2020-07-16T03:52:12Z", "commit": {"oid": "7c8ee1458493fe05c04b0c60732f48d2c131d8b4"}, "state": "APPROVED", "comments": {"totalCount": 2, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wNy0xNlQwMzo1MjoxMlrOGyZJNQ==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wNy0xNlQwMzo1Mzo1M1rOGyZKpA==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1NTQ5Mzk0MQ==", "bodyText": "Observation : The abort Transaction operations on the controller are idempotent, hence calling an abortTransaction() successively will not throw an error.(TnxFailedException or any other error).\nThe controller client will throw a TxnFailedException if the txn id is not found by the controller during abort().", "url": "https://github.com/pravega/pravega/pull/4941#discussion_r455493941", "createdAt": "2020-07-16T03:52:12Z", "author": {"login": "shrids"}, "path": "client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java", "diffHunk": "@@ -145,15 +144,15 @@ public void abort() {\n                         log.debug(\"Got exception while writing to transaction on abort: {}\", e.getMessage());\n                     }\n                 }\n-                getAndHandleExceptions(controller.abortTransaction(stream, txId), RuntimeException::new);\n+                Futures.getThrowingException(controller.abortTransaction(stream, txId));", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "7c8ee1458493fe05c04b0c60732f48d2c131d8b4"}, "originalPosition": 13}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1NTQ5NDMwOA==", "bodyText": "checkTransactionStatus will never throw a TxnFailedException ; as I understand the intent here is to remove redundant RuntimeException wrapping.", "url": "https://github.com/pravega/pravega/pull/4941#discussion_r455494308", "createdAt": "2020-07-16T03:53:53Z", "author": {"login": "shrids"}, "path": "client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java", "diffHunk": "@@ -145,15 +144,15 @@ public void abort() {\n                         log.debug(\"Got exception while writing to transaction on abort: {}\", e.getMessage());\n                     }\n                 }\n-                getAndHandleExceptions(controller.abortTransaction(stream, txId), RuntimeException::new);\n+                Futures.getThrowingException(controller.abortTransaction(stream, txId));\n                 closed.set(true);\n             }\n         }\n \n         @Override\n         public Status checkStatus() {\n             log.info(\"Check transaction status {}\", txId);\n-            return getAndHandleExceptions(controller.checkTransactionStatus(stream, txId), RuntimeException::new);\n+            return Futures.getThrowingException(controller.checkTransactionStatus(stream, txId));", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "7c8ee1458493fe05c04b0c60732f48d2c131d8b4"}, "originalPosition": 22}]}}, {"__typename": "PullRequestReview", "id": "MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDUwMTQ0NjE1", "url": "https://github.com/pravega/pravega/pull/4941#pullrequestreview-450144615", "createdAt": "2020-07-16T19:18:45Z", "commit": {"oid": "7c8ee1458493fe05c04b0c60732f48d2c131d8b4"}, "state": "APPROVED", "comments": {"totalCount": 0, "pageInfo": {"startCursor": null, "endCursor": null, "hasNextPage": false, "hasPreviousPage": false}, "nodes": []}}]}}}, "rateLimit": {"limit": 5000, "remaining": 3957, "cost": 1, "resetAt": "2021-11-01T16:37:27Z"}}}