{"data": {"repository": {"pullRequest": {"id": "MDExOlB1bGxSZXF1ZXN0NDEwODE1NjYx", "number": 3986, "reviewThreads": {"totalCount": 4, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wNS0wNFQwOToxMToxM1rOD46IdQ==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wNS0xMlQwODowMDozNFrOD7iRQQ==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjYwOTk5Mjg1OnYy", "diffSide": "RIGHT", "path": "modules/platform/nuxeo-automation/nuxeo-automation-server/src/main/java/org/nuxeo/ecm/automation/server/jaxrs/adapters/AsyncOperationAdapter.java", "isResolved": false, "comments": {"totalCount": 4, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wNS0wNFQwOToxMToxM1rOGP4S6Q==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wNS0wN1QxNDo1MToxMFrOGSCabg==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxOTMwNDE2OQ==", "bodyText": "So now each normal call to /status costs 2 round trips, one to the transient store to check for an error and one to the kv to get the status.", "url": "https://github.com/nuxeo/nuxeo/pull/3986#discussion_r419304169", "createdAt": "2020-05-04T09:11:13Z", "author": {"login": "bdelbosc"}, "path": "modules/platform/nuxeo-automation/nuxeo-automation-server/src/main/java/org/nuxeo/ecm/automation/server/jaxrs/adapters/AsyncOperationAdapter.java", "diffHunk": "@@ -200,11 +201,11 @@ public OperationException onError(OperationException error) {\n     @GET\n     @Path(\"{executionId}/status\")\n     public Object status(@PathParam(\"executionId\") String executionId) throws IOException, MessagingException {\n+        String error = getError(executionId);", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "c6afaaf1511f21c960a33a18c8b3813cc0f3294a"}, "originalPosition": 21}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxOTQxNjAyMQ==", "bodyText": "The whole problem comes from not checking errors on incomplete async operations. We need to make sure there is no error completed or not.\nNot a dream state but 2 calls vs 1 call is still constant complexity-wise \ud83e\udd37", "url": "https://github.com/nuxeo/nuxeo/pull/3986#discussion_r419416021", "createdAt": "2020-05-04T12:58:39Z", "author": {"login": "NourNuxeo"}, "path": "modules/platform/nuxeo-automation/nuxeo-automation-server/src/main/java/org/nuxeo/ecm/automation/server/jaxrs/adapters/AsyncOperationAdapter.java", "diffHunk": "@@ -200,11 +201,11 @@ public OperationException onError(OperationException error) {\n     @GET\n     @Path(\"{executionId}/status\")\n     public Object status(@PathParam(\"executionId\") String executionId) throws IOException, MessagingException {\n+        String error = getError(executionId);", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxOTMwNDE2OQ=="}, "originalCommit": {"oid": "c6afaaf1511f21c960a33a18c8b3813cc0f3294a"}, "originalPosition": 21}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQyMDE3MTQwMg==", "bodyText": "when setError is called is also calls setCompleted, in which case do we have errors with an execution not marked as completed ?", "url": "https://github.com/nuxeo/nuxeo/pull/3986#discussion_r420171402", "createdAt": "2020-05-05T14:51:48Z", "author": {"login": "nelsonsilva"}, "path": "modules/platform/nuxeo-automation/nuxeo-automation-server/src/main/java/org/nuxeo/ecm/automation/server/jaxrs/adapters/AsyncOperationAdapter.java", "diffHunk": "@@ -200,11 +201,11 @@ public OperationException onError(OperationException error) {\n     @GET\n     @Path(\"{executionId}/status\")\n     public Object status(@PathParam(\"executionId\") String executionId) throws IOException, MessagingException {\n+        String error = getError(executionId);", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxOTMwNDE2OQ=="}, "originalCommit": {"oid": "c6afaaf1511f21c960a33a18c8b3813cc0f3294a"}, "originalPosition": 21}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQyMTU2NzA4Ng==", "bodyText": "when failing while compiling the operation chain, isCompleted() is never true so I guess setCompleted() isn't called. Since isCompleted() conditions the call to getErrors() we never see the error. So we made the call to getErrors() independant and preceding isCompleted(): 028ad6c#diff-632d12880ac130d2edc7fa897f2779eaR205-L207", "url": "https://github.com/nuxeo/nuxeo/pull/3986#discussion_r421567086", "createdAt": "2020-05-07T14:51:10Z", "author": {"login": "NourNuxeo"}, "path": "modules/platform/nuxeo-automation/nuxeo-automation-server/src/main/java/org/nuxeo/ecm/automation/server/jaxrs/adapters/AsyncOperationAdapter.java", "diffHunk": "@@ -200,11 +201,11 @@ public OperationException onError(OperationException error) {\n     @GET\n     @Path(\"{executionId}/status\")\n     public Object status(@PathParam(\"executionId\") String executionId) throws IOException, MessagingException {\n+        String error = getError(executionId);", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxOTMwNDE2OQ=="}, "originalCommit": {"oid": "c6afaaf1511f21c960a33a18c8b3813cc0f3294a"}, "originalPosition": 21}]}}, {"id": "MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjYxNTUxODI4OnYy", "diffSide": "RIGHT", "path": "modules/platform/nuxeo-automation/nuxeo-automation-server/src/main/java/org/nuxeo/ecm/automation/server/jaxrs/adapters/AsyncOperationAdapter.java", "isResolved": true, "comments": {"totalCount": 1, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wNS0wNVQxNDo0MjozMlrOGQsxLA==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wNS0wNVQxNDo0MjozMlrOGQsxLA==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQyMDE2Mzg4NA==", "bodyText": "I would have added a new method setError(String, Throwable) to handle the unwrapException logic (and deprecate the existing setError method probably as it won't be used anymore).", "url": "https://github.com/nuxeo/nuxeo/pull/3986#discussion_r420163884", "createdAt": "2020-05-05T14:42:32Z", "author": {"login": "troger"}, "path": "modules/platform/nuxeo-automation/nuxeo-automation-server/src/main/java/org/nuxeo/ecm/automation/server/jaxrs/adapters/AsyncOperationAdapter.java", "diffHunk": "@@ -164,7 +165,7 @@ public void onOperationExit(Object output) {\n \n             @Override\n             public OperationException onError(OperationException error) {\n-                setError(executionId, error.getMessage());\n+                setError(executionId, ExceptionHelper.unwrapException(error).getMessage());", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "028ad6c66f4120654dfdaec4b0391cde20220e1f"}, "originalPosition": 13}]}}, {"id": "MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjYzNzUxNzE4OnYy", "diffSide": "RIGHT", "path": "modules/platform/nuxeo-automation/nuxeo-automation-server/src/main/java/org/nuxeo/ecm/automation/server/jaxrs/adapters/AsyncOperationAdapter.java", "isResolved": false, "comments": {"totalCount": 3, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wNS0xMlQwNzo1NDozMlrOGT6dhw==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wNS0xMlQwODozMzo1NlrOGT791A==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQyMzUzMzk1OQ==", "bodyText": "You should add @deprecated since 11.1, because unused and use the deprecated method in the new one as the code is the same.", "url": "https://github.com/nuxeo/nuxeo/pull/3986#discussion_r423533959", "createdAt": "2020-05-12T07:54:32Z", "author": {"login": "kevinleturc"}, "path": "modules/platform/nuxeo-automation/nuxeo-automation-server/src/main/java/org/nuxeo/ecm/automation/server/jaxrs/adapters/AsyncOperationAdapter.java", "diffHunk": "@@ -289,6 +290,13 @@ protected void enterMethod(String executionId, InvokableMethod method) {\n         }\n     }\n \n+    protected void setError(String executionId, Throwable t) {\n+        getTransientStore().putParameter(executionId, TRANSIENT_STORE_ERROR,\n+                ExceptionHelper.unwrapException(t).getMessage());\n+        setCompleted(executionId);\n+    }\n+\n+    @Deprecated\n     protected void setError(String executionId, String error) {\n         getTransientStore().putParameter(executionId, TRANSIENT_STORE_ERROR, error);\n         setCompleted(executionId);", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "ec8c4cbc95ec8f7349f81f934e681ad112f299a7"}, "originalPosition": 55}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQyMzU1NzM4Mw==", "bodyText": "I was wondering what would happen when the deprecated method is automatically removed. I guess there is some mechanism around that ?", "url": "https://github.com/nuxeo/nuxeo/pull/3986#discussion_r423557383", "createdAt": "2020-05-12T08:31:54Z", "author": {"login": "NourNuxeo"}, "path": "modules/platform/nuxeo-automation/nuxeo-automation-server/src/main/java/org/nuxeo/ecm/automation/server/jaxrs/adapters/AsyncOperationAdapter.java", "diffHunk": "@@ -289,6 +290,13 @@ protected void enterMethod(String executionId, InvokableMethod method) {\n         }\n     }\n \n+    protected void setError(String executionId, Throwable t) {\n+        getTransientStore().putParameter(executionId, TRANSIENT_STORE_ERROR,\n+                ExceptionHelper.unwrapException(t).getMessage());\n+        setCompleted(executionId);\n+    }\n+\n+    @Deprecated\n     protected void setError(String executionId, String error) {\n         getTransientStore().putParameter(executionId, TRANSIENT_STORE_ERROR, error);\n         setCompleted(executionId);", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQyMzUzMzk1OQ=="}, "originalCommit": {"oid": "ec8c4cbc95ec8f7349f81f934e681ad112f299a7"}, "originalPosition": 55}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQyMzU1ODYxMg==", "bodyText": "Deprecated methods are not removed automatically. This is us who remove them during a Cleanup / Format commit or a dedicated ticket if there's a lot to remove.", "url": "https://github.com/nuxeo/nuxeo/pull/3986#discussion_r423558612", "createdAt": "2020-05-12T08:33:56Z", "author": {"login": "kevinleturc"}, "path": "modules/platform/nuxeo-automation/nuxeo-automation-server/src/main/java/org/nuxeo/ecm/automation/server/jaxrs/adapters/AsyncOperationAdapter.java", "diffHunk": "@@ -289,6 +290,13 @@ protected void enterMethod(String executionId, InvokableMethod method) {\n         }\n     }\n \n+    protected void setError(String executionId, Throwable t) {\n+        getTransientStore().putParameter(executionId, TRANSIENT_STORE_ERROR,\n+                ExceptionHelper.unwrapException(t).getMessage());\n+        setCompleted(executionId);\n+    }\n+\n+    @Deprecated\n     protected void setError(String executionId, String error) {\n         getTransientStore().putParameter(executionId, TRANSIENT_STORE_ERROR, error);\n         setCompleted(executionId);", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQyMzUzMzk1OQ=="}, "originalCommit": {"oid": "ec8c4cbc95ec8f7349f81f934e681ad112f299a7"}, "originalPosition": 55}]}}, {"id": "MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjYzNzU0MDQ5OnYy", "diffSide": "RIGHT", "path": "modules/platform/nuxeo-automation/nuxeo-automation-test/src/test/java/org/nuxeo/ecm/automation/server/test/AsyncOperationAdapterTest.java", "isResolved": false, "comments": {"totalCount": 1, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wNS0xMlQwODowMDozNFrOGT6sVg==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wNS0xMlQwODowMDozNFrOGT6sVg==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQyMzUzNzc1MA==", "bodyText": "Can we just put \"{}\" without calling the MAPPER? writeValueAsString is used to serialize an object to JSON (or other), here you're giving to it a String. My first thought is: writing a string as string will return the input string. If it's not the case, having the final value in the test will help us to understand what makes it fail and what we want to control/catch.", "url": "https://github.com/nuxeo/nuxeo/pull/3986#discussion_r423537750", "createdAt": "2020-05-12T08:00:34Z", "author": {"login": "kevinleturc"}, "path": "modules/platform/nuxeo-automation/nuxeo-automation-test/src/test/java/org/nuxeo/ecm/automation/server/test/AsyncOperationAdapterTest.java", "diffHunk": "@@ -222,6 +222,19 @@ public void testAsyncBulkAction() throws Exception {\n         assertEquals(\"foo\", getTitle(folder));\n     }\n \n+    @Test\n+    public void testFailingBulkAction() throws Exception {\n+        String result = async.newRequest(BulkRunAction.ID) //\n+                             .set(\"action\", AutomationBulkAction.ACTION_NAME)\n+                             .set(\"query\", \"SELECT * FROM Folder\")\n+                             .set(\"bucketSize\", \"10\")\n+                             .set(\"batchSize\", \"5\")\n+                             .set(\"parameters\", MAPPER.writeValueAsString(\"{}\"))", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "ec8c4cbc95ec8f7349f81f934e681ad112f299a7"}, "originalPosition": 20}]}}]}}}, "rateLimit": {"limit": 5000, "remaining": 4198, "cost": 1, "resetAt": "2021-11-03T18:41:40Z"}}}