{"pr_number": 1950, "pr_title": "HADOOP-16586. ITestS3GuardFsck, others fails when run using a local m\u2026", "pr_createdAt": "2020-04-10T14:53:09Z", "pr_url": "https://github.com/apache/hadoop/pull/1950", "timeline": [{"oid": "867d9ed0682b26ab3c518f5d71855e50dc054d5c", "url": "https://github.com/apache/hadoop/commit/867d9ed0682b26ab3c518f5d71855e50dc054d5c", "message": "HADOOP-16586. ITestS3GuardFsck, others fails when run using a local metastore.", "committedDate": "2020-04-10T14:50:49Z", "type": "commit"}, {"oid": "18131caecc24a79c047ba0fd55395f054466ee90", "url": "https://github.com/apache/hadoop/commit/18131caecc24a79c047ba0fd55395f054466ee90", "message": "addressed checkstyle warnings.", "committedDate": "2020-04-10T22:32:35Z", "type": "commit"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMTM0OTc3MA==", "url": "https://github.com/apache/hadoop/pull/1950#discussion_r411349770", "bodyText": "not sure the expansion here is needed..,you know how imports are such a backporting troublespot.\nin fact, given there's no other diff to this class, I'm not sure this file needs changing at all", "author": "steveloughran", "createdAt": "2020-04-20T12:49:23Z", "path": "hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/impl/ITestPartialRenamesDeletes.java", "diffHunk": "@@ -54,7 +54,12 @@\n import static org.apache.hadoop.fs.contract.ContractTestUtils.*;\n import static org.apache.hadoop.fs.s3a.Constants.*;\n import static org.apache.hadoop.fs.s3a.S3ATestUtils.MetricDiff;\n-import static org.apache.hadoop.fs.s3a.S3ATestUtils.*;\n+import static org.apache.hadoop.fs.s3a.S3ATestUtils.assume;", "originalCommit": "18131caecc24a79c047ba0fd55395f054466ee90", "replyToReviewId": null, "replies": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxNjMzMTMyNA==", "url": "https://github.com/apache/hadoop/pull/1950#discussion_r416331324", "bodyText": "I got issue on getting test bucket name even if test.fs.s3a.name was defined in the test conf and othter itests worked.\njava.lang.NullPointerException: No test bucket\n\tat com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)\n\tat org.apache.hadoop.fs.s3a.S3ATestUtils.getTestBucketName(S3ATestUtils.java:739)\n\tat org.apache.hadoop.fs.s3a.impl.ITestPartialRenamesDeletes.createConfiguration(ITestPartialRenamesDeletes.java:326)\n\nI suspected the configuration reloading in S3ATestUtils as the cause. The change is leftover of trial-and-error. Since I can not reproduce the issue now, I will revert this part.", "author": "iwasakims", "createdAt": "2020-04-28T05:11:56Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMTM0OTc3MA=="}], "type": "inlineReview"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMTM1MDk2Nw==", "url": "https://github.com/apache/hadoop/pull/1950#discussion_r411350967", "bodyText": "why did you cut this assertion?", "author": "steveloughran", "createdAt": "2020-04-20T12:51:12Z", "path": "hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/ITestS3GuardToolLocal.java", "diffHunk": "@@ -97,7 +98,6 @@ public void testImportCommand() throws Exception {\n         .getListing().size());\n     assertEquals(\"Expected 2 items: empty directory and a parent directory\", 2,\n         ms.listChildren(parent).getListing().size());\n-    assertTrue(children.isAuthoritative());", "originalCommit": "18131caecc24a79c047ba0fd55395f054466ee90", "replyToReviewId": null, "replies": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxNjMzNjM3OQ==", "url": "https://github.com/apache/hadoop/pull/1950#discussion_r416336379", "bodyText": "This looks wrong assertion. No -authoritative flag is given in the cmd.", "author": "iwasakims", "createdAt": "2020-04-28T05:26:59Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMTM1MDk2Nw=="}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxNjM0MTAxMw==", "url": "https://github.com/apache/hadoop/pull/1950#discussion_r416341013", "bodyText": "Actually I got assertion error when I ran the test with fs.s3a.metadatastore.impl=org.apache.hadoop.fs.s3a.s3guard.LocalMetadataStore.\n$ mvn verify -Ds3guard -Dtest=x -Dit.test=ITestS3GuardToolLocal\n...\n[ERROR] Tests run: 33, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 208.832 s <<< FAILURE! - in org.apache.hadoop.fs.s3a.s3guard.ITestS3GuardToolLocal\n[ERROR] testImportCommand(org.apache.hadoop.fs.s3a.s3guard.ITestS3GuardToolLocal)  Time elapsed: 15.872 s  <<< FAILURE!\njava.lang.AssertionError\n\tat org.apache.hadoop.fs.s3a.s3guard.ITestS3GuardToolLocal.testImportCommand(ITestS3GuardToolLocal.java:101)", "author": "iwasakims", "createdAt": "2020-04-28T05:40:28Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMTM1MDk2Nw=="}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxODQ4MzU5Mw==", "url": "https://github.com/apache/hadoop/pull/1950#discussion_r418483593", "bodyText": "probably is wrong then :)", "author": "steveloughran", "createdAt": "2020-05-01T09:53:28Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMTM1MDk2Nw=="}], "type": "inlineReview"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMTM1MjYzMg==", "url": "https://github.com/apache/hadoop/pull/1950#discussion_r411352632", "bodyText": "if this is triggering failures, I'm not seeing them -but then I do have fs.s3a.bucket.probe == 0....it's probably not triggering any bucket probe at all. For consistent failures here, the config we run with should have that option set to 2, \"use v2 probe on instantiation\".", "author": "steveloughran", "createdAt": "2020-04-20T12:53:45Z", "path": "hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/ITestS3GuardToolLocal.java", "diffHunk": "@@ -165,18 +165,19 @@ public void testImportNoFilesystem() throws Throwable {\n \n   @Test\n   public void testInfoBucketAndRegionNoFS() throws Throwable {\n-    intercept(FileNotFoundException.class,\n+    intercept(UnknownStoreException.class,", "originalCommit": "18131caecc24a79c047ba0fd55395f054466ee90", "replyToReviewId": null, "replies": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxNjM1NDYwNQ==", "url": "https://github.com/apache/hadoop/pull/1950#discussion_r416354605", "bodyText": "v2 prove was used as a default value when I ran the test.\n  public static final int S3A_BUCKET_PROBE_DEFAULT = 2;\n\nThe reaseon you did not see this may be that the ITestS3GuardToolLocal was just skipped. You are using DynamoDBMetadataStore rather than LocalMetadataStore?", "author": "iwasakims", "createdAt": "2020-04-28T06:15:21Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMTM1MjYzMg=="}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxNjQ2OTMyNg==", "url": "https://github.com/apache/hadoop/pull/1950#discussion_r416469326", "bodyText": "yeah, generally", "author": "steveloughran", "createdAt": "2020-04-28T09:31:14Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMTM1MjYzMg=="}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxODQ4MzkzNg==", "url": "https://github.com/apache/hadoop/pull/1950#discussion_r418483936", "bodyText": "we should probably unset bucket probe options too & switch to the default (2) value; avoid differences in init behaviour", "author": "steveloughran", "createdAt": "2020-05-01T09:54:30Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMTM1MjYzMg=="}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQyNDA5OTY1MQ==", "url": "https://github.com/apache/hadoop/pull/1950#discussion_r424099651", "bodyText": "This was addressed in createConfiguration above.", "author": "iwasakims", "createdAt": "2020-05-12T23:58:26Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMTM1MjYzMg=="}], "type": "inlineReview"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMTM1MzU3MA==", "url": "https://github.com/apache/hadoop/pull/1950#discussion_r411353570", "bodyText": "if this is triggering bucket probe failures, it's not doing the -ve arg check. So here we should either switch to a probe option of 0, or just cut the test entirely. I'm almost going for the latter given the way people should be creating tables is with read = write =0 for on-demand use", "author": "steveloughran", "createdAt": "2020-04-20T12:55:09Z", "path": "hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/ITestS3GuardToolLocal.java", "diffHunk": "@@ -165,18 +165,19 @@ public void testImportNoFilesystem() throws Throwable {\n \n   @Test\n   public void testInfoBucketAndRegionNoFS() throws Throwable {\n-    intercept(FileNotFoundException.class,\n+    intercept(UnknownStoreException.class,\n         () -> run(BucketInfo.NAME, \"-meta\",\n             LOCAL_METADATA, \"-region\",\n             \"any-region\", S3A_THIS_BUCKET_DOES_NOT_EXIST));\n   }\n \n   @Test\n   public void testInitNegativeRead() throws Throwable {\n-    runToFailure(INVALID_ARGUMENT,\n-        Init.NAME, \"-meta\", LOCAL_METADATA, \"-region\",\n-        \"eu-west-1\",\n-        READ_FLAG, \"-10\");\n+    intercept(CommandFormat.UnknownOptionException.class,", "originalCommit": "18131caecc24a79c047ba0fd55395f054466ee90", "replyToReviewId": null, "replies": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxNjM0NjMxMQ==", "url": "https://github.com/apache/hadoop/pull/1950#discussion_r416346311", "bodyText": "I agree to remove the test. The error caused by treating -10 as option rather than option's value since it startsWith(\"-\"). The read flag does not need to handle negative value.", "author": "iwasakims", "createdAt": "2020-04-28T05:54:35Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMTM1MzU3MA=="}], "type": "inlineReview"}, {"oid": "2fd5ae9a96299870899611c734b139f5a085f1bd", "url": "https://github.com/apache/hadoop/commit/2fd5ae9a96299870899611c734b139f5a085f1bd", "message": "removed unnecessary imports and test based on the review comment.", "committedDate": "2020-04-28T06:16:34Z", "type": "commit"}, {"oid": "cded221938e0d4c20f0d3db11770191ccc29ef47", "url": "https://github.com/apache/hadoop/commit/cded221938e0d4c20f0d3db11770191ccc29ef47", "message": "addressing checkstyle warning: Unused import.", "committedDate": "2020-04-28T07:59:31Z", "type": "commit"}, {"oid": "04479c24cc27ec543dfe48a4406d19f7c3643b8c", "url": "https://github.com/apache/hadoop/commit/04479c24cc27ec543dfe48a4406d19f7c3643b8c", "message": "ITestS3GuardToolLocal should always use LocalMetadataStore rather than skipping the tests based on fs.s3a.metadatastore.impl.", "committedDate": "2020-04-28T12:49:42Z", "type": "commit"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxODQ4MzQyNg==", "url": "https://github.com/apache/hadoop/pull/1950#discussion_r418483426", "bodyText": "need to use the removeBaseAndBucketOverrides() code in S3ATestUtils to make sure that any per-bucket setting has turned it on. Look for other uses to see what to do", "author": "steveloughran", "createdAt": "2020-05-01T09:52:50Z", "path": "hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/s3guard/ITestS3GuardToolLocal.java", "diffHunk": "@@ -57,13 +59,18 @@\n   private static final String[] ABORT_FORCE_OPTIONS = new String[] {\"-abort\",\n       \"-force\", \"-verbose\"};\n \n+  @Override\n+  protected Configuration createConfiguration() {\n+    Configuration conf = super.createConfiguration();\n+    conf.set(S3_METADATA_STORE_IMPL, S3GUARD_METASTORE_LOCAL);", "originalCommit": "04479c24cc27ec543dfe48a4406d19f7c3643b8c", "replyToReviewId": null, "replies": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxODc4MTM5OQ==", "url": "https://github.com/apache/hadoop/pull/1950#discussion_r418781399", "bodyText": "Thanks. I added code to reset fs.s3a.metadatastore.impl and fs.s3a.bucket.probe.", "author": "iwasakims", "createdAt": "2020-05-01T23:45:49Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxODQ4MzQyNg=="}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQyMDg4MjYzOQ==", "url": "https://github.com/apache/hadoop/pull/1950#discussion_r420882639", "bodyText": "thanks. FWIW that removeBaseAndBucket call is varags; you can remove as many as you need in one go. Code is fine as as is though", "author": "steveloughran", "createdAt": "2020-05-06T15:27:50Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxODQ4MzQyNg=="}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQyMTE2MDI0MA==", "url": "https://github.com/apache/hadoop/pull/1950#discussion_r421160240", "bodyText": "Sure. I removed the duplicate call.", "author": "iwasakims", "createdAt": "2020-05-07T00:00:23Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxODQ4MzQyNg=="}], "type": "inlineReview"}, {"oid": "5c646e9ada49a2674f12c94b15f77098d3266dcf", "url": "https://github.com/apache/hadoop/commit/5c646e9ada49a2674f12c94b15f77098d3266dcf", "message": "leveraging S3ATestUtils.removeBaseAndBucketOverrides to clear per bucket config.", "committedDate": "2020-05-01T23:40:35Z", "type": "commit"}, {"oid": "3d57653a139a313bb20eee88a52c4cdccc5ca1b1", "url": "https://github.com/apache/hadoop/commit/3d57653a139a313bb20eee88a52c4cdccc5ca1b1", "message": "removed duplicate call for clearing the configuration.", "committedDate": "2020-05-06T23:56:46Z", "type": "commit"}]}