{"pr_number": 12374, "pr_title": "[FLINK-17992][checkpointing] Exception from RemoteInputChannel#onBuffer should not fail the whole NetworkClientHandler", "pr_createdAt": "2020-05-28T07:10:52Z", "pr_url": "https://github.com/apache/flink/pull/12374", "timeline": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQzMTcwNzA3OQ==", "url": "https://github.com/apache/flink/pull/12374#discussion_r431707079", "bodyText": "assertEquals(expectedMessage, ignored.getMessage()) ?", "author": "Jiayi-Liao", "createdAt": "2020-05-28T09:35:21Z", "path": "flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandlerTest.java", "diffHunk": "@@ -486,6 +488,47 @@ public void testReadBufferResponseAfterRemovingChannel() throws Exception {\n \t\ttestReadBufferResponseWithReleasingOrRemovingChannel(true, false);\n \t}\n \n+\t@Test\n+\tpublic void testRemoteInputChannelOnBufferException() throws Exception {\n+\t\t// Setup\n+\t\tfinal int bufferSize = 1024;\n+\t\tfinal String expectedMessage = \"test exception on buffer\";\n+\t\tfinal NetworkBufferPool networkBufferPool = new NetworkBufferPool(10, bufferSize, 2);\n+\t\tfinal SingleInputGate inputGate = createSingleInputGate(1, networkBufferPool);\n+\t\tfinal RemoteInputChannel inputChannel = new TestRemoteInputChannelForError(inputGate, expectedMessage);\n+\t\tfinal CreditBasedPartitionRequestClientHandler handler = new CreditBasedPartitionRequestClientHandler();\n+\n+\t\ttry {\n+\t\t\tinputGate.setInputChannels(inputChannel);\n+\t\t\tinputGate.assignExclusiveSegments();\n+\t\t\tinputGate.requestPartitions();\n+\t\t\thandler.addInputChannel(inputChannel);\n+\n+\t\t\tfinal BufferResponse bufferResponse = createBufferResponse(\n+\t\t\t\tTestBufferFactory.createBuffer(bufferSize),\n+\t\t\t\t0,\n+\t\t\t\tinputChannel.getInputChannelId(),\n+\t\t\t\t1,\n+\t\t\t\tnew NetworkBufferAllocator(handler));\n+\n+\t\t\t// It will trigger an expected exception from TestRemoteInputChannelForError#onBuffer\n+\t\t\thandler.channelRead(null, bufferResponse);\n+\n+\t\t\t// The handler should not be tagged as error for above excepted exception\n+\t\t\thandler.checkError();\n+\n+\t\t\ttry {\n+\t\t\t\t// The input channel should be tagged as error and the respective exception is thrown via #getNext\n+\t\t\t\tinputGate.getNext();\n+\t\t\t} catch (IOException ignored) {\n+\t\t\t\tassertEquals(\"exception for test\", ignored.getMessage());", "originalCommit": "eeaa680286b6dd389acebbf1d8695ba94ff5ec59", "replyToReviewId": null, "replies": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQzMTc2NDc5Mg==", "url": "https://github.com/apache/flink/pull/12374#discussion_r431764792", "bodyText": "yes, forgot updating it while introducing the expectedMessage variable.", "author": "zhijiangW", "createdAt": "2020-05-28T11:25:11Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQzMTcwNzA3OQ=="}], "type": "inlineReview", "revised_code": {"commit": "a4a4f7c5d2e2db50eda956b89b6b38e0f0c2e0b3", "chunk": "diff --git a/flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandlerTest.java b/flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandlerTest.java\nindex 782fdd4440b..d40d7ff97b9 100644\n--- a/flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandlerTest.java\n+++ b/flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandlerTest.java\n\n@@ -521,7 +521,7 @@ public class CreditBasedPartitionRequestClientHandlerTest {\n \t\t\t\t// The input channel should be tagged as error and the respective exception is thrown via #getNext\n \t\t\t\tinputGate.getNext();\n \t\t\t} catch (IOException ignored) {\n-\t\t\t\tassertEquals(\"exception for test\", ignored.getMessage());\n+\t\t\t\tassertEquals(expectedMessage, ignored.getMessage());\n \t\t\t}\n \t\t} finally {\n \t\t\t// Cleanup\n"}}, {"oid": "a4a4f7c5d2e2db50eda956b89b6b38e0f0c2e0b3", "url": "https://github.com/apache/flink/commit/a4a4f7c5d2e2db50eda956b89b6b38e0f0c2e0b3", "message": "[FLINK-17992][checkpointing] Exception from RemoteInputChannel#onBuffer should not fail the whole NetworkClientHandler\n\nRemoteInputChannel#onBuffer is invoked by CreditBasedPartitionRequestClientHandler while receiving and decoding the network data. #onBuffer can\nthrow exceptions which would tag the error in client handler and fail all the added input channels inside handler. Then it would cause a tricky\npotential issue as following.\n\nIf the RemoteInputChannel is canceling by canceler thread, then the task thread might exit early than canceler thread terminate. That means the\nPartitionRequestClient might not be closed (triggered by canceler thread) while the new task attempt is already deployed into the same TaskManager.\nTherefore the new task might reuse the previous PartitionRequestClient while requesting partitions, but note that the respective client handler was\nalready tagged an error before during above RemoteInputChannel#onBuffer, to cause the next round unnecessary failover.\n\nThe solution is to only fail the respective task when its internal RemoteInputChannel#onBuffer throws any exceptions instead of failing the whole\nchannels inside client handler, then the client is still healthy and can also be reused by other input channels as long as it is not released yet.", "committedDate": "2020-05-28T11:28:11Z", "type": "forcePushed"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQzMTc3NDQ1Mw==", "url": "https://github.com/apache/flink/pull/12374#discussion_r431774453", "bodyText": "nit rename to:\ntestDoNotFailHandlerOnSingleChannelFailure()\nor\ntestDoNotFailHandlerOnSingleChannelOnBufferFailure()\n? I think that would convey the purpose of the test better, instead of describing what's happening inside.", "author": "pnowojski", "createdAt": "2020-05-28T11:44:33Z", "path": "flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandlerTest.java", "diffHunk": "@@ -486,6 +488,47 @@ public void testReadBufferResponseAfterRemovingChannel() throws Exception {\n \t\ttestReadBufferResponseWithReleasingOrRemovingChannel(true, false);\n \t}\n \n+\t@Test\n+\tpublic void testRemoteInputChannelOnBufferException() throws Exception {", "originalCommit": "a4a4f7c5d2e2db50eda956b89b6b38e0f0c2e0b3", "replyToReviewId": null, "replies": null, "type": "inlineReview", "revised_code": {"commit": "59ce42b5686283f5eb3b0118c66d24dda2c0096a", "chunk": "diff --git a/flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandlerTest.java b/flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandlerTest.java\nindex d40d7ff97b9..8cfa4e40aa4 100644\n--- a/flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandlerTest.java\n+++ b/flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandlerTest.java\n\n@@ -489,7 +489,7 @@ public class CreditBasedPartitionRequestClientHandlerTest {\n \t}\n \n \t@Test\n-\tpublic void testRemoteInputChannelOnBufferException() throws Exception {\n+\tpublic void testDoNotFailHandlerOnSingleChannelFailure() throws Exception {\n \t\t// Setup\n \t\tfinal int bufferSize = 1024;\n \t\tfinal String expectedMessage = \"test exception on buffer\";\n"}}, {"oid": "59ce42b5686283f5eb3b0118c66d24dda2c0096a", "url": "https://github.com/apache/flink/commit/59ce42b5686283f5eb3b0118c66d24dda2c0096a", "message": "[FLINK-17992][checkpointing] Exception from RemoteInputChannel#onBuffer should not fail the whole NetworkClientHandler\n\nRemoteInputChannel#onBuffer is invoked by CreditBasedPartitionRequestClientHandler while receiving and decoding the network data. #onBuffer can\nthrow exceptions which would tag the error in client handler and fail all the added input channels inside handler. Then it would cause a tricky\npotential issue as following.\n\nIf the RemoteInputChannel is canceling by canceler thread, then the task thread might exit early than canceler thread terminate. That means the\nPartitionRequestClient might not be closed (triggered by canceler thread) while the new task attempt is already deployed into the same TaskManager.\nTherefore the new task might reuse the previous PartitionRequestClient while requesting partitions, but note that the respective client handler was\nalready tagged an error before during above RemoteInputChannel#onBuffer, to cause the next round unnecessary failover.\n\nThe solution is to only fail the respective task when its internal RemoteInputChannel#onBuffer throws any exceptions instead of failing the whole\nchannels inside client handler, then the client is still healthy and can also be reused by other input channels as long as it is not released yet.", "committedDate": "2020-05-29T02:36:19Z", "type": "commit"}, {"oid": "59ce42b5686283f5eb3b0118c66d24dda2c0096a", "url": "https://github.com/apache/flink/commit/59ce42b5686283f5eb3b0118c66d24dda2c0096a", "message": "[FLINK-17992][checkpointing] Exception from RemoteInputChannel#onBuffer should not fail the whole NetworkClientHandler\n\nRemoteInputChannel#onBuffer is invoked by CreditBasedPartitionRequestClientHandler while receiving and decoding the network data. #onBuffer can\nthrow exceptions which would tag the error in client handler and fail all the added input channels inside handler. Then it would cause a tricky\npotential issue as following.\n\nIf the RemoteInputChannel is canceling by canceler thread, then the task thread might exit early than canceler thread terminate. That means the\nPartitionRequestClient might not be closed (triggered by canceler thread) while the new task attempt is already deployed into the same TaskManager.\nTherefore the new task might reuse the previous PartitionRequestClient while requesting partitions, but note that the respective client handler was\nalready tagged an error before during above RemoteInputChannel#onBuffer, to cause the next round unnecessary failover.\n\nThe solution is to only fail the respective task when its internal RemoteInputChannel#onBuffer throws any exceptions instead of failing the whole\nchannels inside client handler, then the client is still healthy and can also be reused by other input channels as long as it is not released yet.", "committedDate": "2020-05-29T02:36:19Z", "type": "forcePushed"}]}