{"pr_number": 1923, "pr_title": "Hadoop 16857. ABFS: Stop CustomTokenProvider retry logic to depend on AbfsRestOp retry policy", "pr_createdAt": "2020-03-30T09:29:58Z", "pr_url": "https://github.com/apache/hadoop/pull/1923", "timeline": [{"oid": "8b1a382bdbe1f3105063214012f6d8ecefa5fb14", "url": "https://github.com/apache/hadoop/commit/8b1a382bdbe1f3105063214012f6d8ecefa5fb14", "message": "Stop retries from AbfsRestOperation due to exception from CustomTokenProvider", "committedDate": "2020-03-30T09:19:31Z", "type": "commit"}, {"oid": "9d75c4c6612a7402ecd4d45ad6f3491677c75014", "url": "https://github.com/apache/hadoop/commit/9d75c4c6612a7402ecd4d45ad6f3491677c75014", "message": "Merge branch 'trunk' into HADOOP-16857", "committedDate": "2020-03-30T09:28:41Z", "type": "commit"}, {"oid": "3af12949021ae16164f05f1f28bb08cb44ffdf20", "url": "https://github.com/apache/hadoop/commit/3af12949021ae16164f05f1f28bb08cb44ffdf20", "message": "Checkstyle fixes.", "committedDate": "2020-04-06T08:54:45Z", "type": "commit"}, {"oid": "d917f7cc3b25c3382c81139c5af50b9497b0ac89", "url": "https://github.com/apache/hadoop/commit/d917f7cc3b25c3382c81139c5af50b9497b0ac89", "message": "Fixing checkstyle issues for erro NoWhitespacebefore", "committedDate": "2020-04-06T09:43:39Z", "type": "commit"}, {"oid": "c4aa751ecd434256414a338f9b35c3173ceca7cf", "url": "https://github.com/apache/hadoop/commit/c4aa751ecd434256414a338f9b35c3173ceca7cf", "message": "Merge branch 'trunk' into HADOOP-16857", "committedDate": "2020-04-06T10:50:03Z", "type": "commit"}, {"oid": "57bb403440aa9a4638a887c904f099709bc4ae9b", "url": "https://github.com/apache/hadoop/commit/57bb403440aa9a4638a887c904f099709bc4ae9b", "message": "Checkstyle issues for MagicNumber errors", "committedDate": "2020-04-07T04:27:32Z", "type": "commit"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQwNTI4NDQ4MA==", "url": "https://github.com/apache/hadoop/pull/1923#discussion_r405284480", "bodyText": "Throwable might be safer?", "author": "DadanielZ", "createdAt": "2020-04-08T06:23:23Z", "path": "hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/oauth2/CustomTokenProviderAdapter.java", "diffHunk": "@@ -46,16 +48,53 @@\n    *\n    * @param adaptee the custom token provider\n    */\n-  public CustomTokenProviderAdapter(CustomTokenProviderAdaptee adaptee) {\n+  public CustomTokenProviderAdapter(CustomTokenProviderAdaptee adaptee, int customTokenFetchRetryCount) {\n     Preconditions.checkNotNull(adaptee, \"adaptee\");\n     this.adaptee = adaptee;\n+    fetchTokenRetryCount = customTokenFetchRetryCount;\n   }\n \n   protected AzureADToken refreshToken() throws IOException {\n     LOG.debug(\"AADToken: refreshing custom based token\");\n \n     AzureADToken azureADToken = new AzureADToken();\n-    azureADToken.setAccessToken(adaptee.getAccessToken());\n+\n+    String accessToken = null;\n+\n+    Exception ex;\n+    boolean succeeded = false;\n+    // Custom token providers should have their own retry policies,\n+    // Providing a linear retry option for the the retry count\n+    // mentioned in config \"fs.azure.custom.token.fetch.retry.count\"\n+    int retryCount = fetchTokenRetryCount;\n+    do {\n+      ex = null;\n+      try {\n+        accessToken = adaptee.getAccessToken();\n+        LOG.trace(\"CustomTokenProvider Access token fetch was successful with retry count {}\", retryCount);\n+      } catch (Exception e) {", "originalCommit": "57bb403440aa9a4638a887c904f099709bc4ae9b", "replyToReviewId": null, "replies": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMjUyMDYyNw==", "url": "https://github.com/apache/hadoop/pull/1923#discussion_r412520627", "bodyText": "I checked across few articles and recommendation seems to be to not catch throwable. At this point we need to catch any exception coming from the CustomTokenProvider.\nPasting couple of links I referenced:\n\nhttps://stackify.com/best-practices-exceptions-java/ => scroll to \"6. Don\u2019t Catch Throwable\"\nhttps://www.baeldung.com/java-catch-throwable-bad-practice#catching-throwable\n\nPlease let me know if you still think this needs to be changed.", "author": "snvijaya", "createdAt": "2020-04-21T21:59:03Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQwNTI4NDQ4MA=="}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMjY2MjAwNw==", "url": "https://github.com/apache/hadoop/pull/1923#discussion_r412662007", "bodyText": "yea Exception should be enough", "author": "DadanielZ", "createdAt": "2020-04-22T04:32:43Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQwNTI4NDQ4MA=="}], "type": "inlineReview", "revised_code": {"commit": "716c8d80c7553da95efd277a2bf5341a6d83de26", "chunk": "diff --git a/hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/oauth2/CustomTokenProviderAdapter.java b/hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/oauth2/CustomTokenProviderAdapter.java\nindex 7989080f1f8..6f2ca0d5586 100644\n--- a/hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/oauth2/CustomTokenProviderAdapter.java\n+++ b/hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/oauth2/CustomTokenProviderAdapter.java\n\n@@ -71,9 +71,11 @@ protected AzureADToken refreshToken() throws IOException {\n       ex = null;\n       try {\n         accessToken = adaptee.getAccessToken();\n-        LOG.trace(\"CustomTokenProvider Access token fetch was successful with retry count {}\", retryCount);\n+        LOG.trace(\"CustomTokenProvider Access token fetch was successful with retry count {}\",\n+            (fetchTokenRetryCount - retryCount));\n       } catch (Exception e) {\n-        LOG.debug(\"CustomTokenProvider Access token fetch failed with retry count {}\", retryCount);\n+        LOG.debug(\"CustomTokenProvider Access token fetch failed with retry count {}\",\n+            (fetchTokenRetryCount - retryCount));\n         ex = e;\n       }\n \n"}}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQwNTI4OTgwOA==", "url": "https://github.com/apache/hadoop/pull/1923#discussion_r405289808", "bodyText": "Is it necessary to add trace log here? it affects the perf for all rereshToken requests including those succeed without retry.\nAnd the retryCount in the message is confusing,  the total times of retries that have been executed should be fetchTokenRetryCount - retryCount, same for the msg in the catch block.", "author": "DadanielZ", "createdAt": "2020-04-08T06:37:38Z", "path": "hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/oauth2/CustomTokenProviderAdapter.java", "diffHunk": "@@ -46,16 +48,53 @@\n    *\n    * @param adaptee the custom token provider\n    */\n-  public CustomTokenProviderAdapter(CustomTokenProviderAdaptee adaptee) {\n+  public CustomTokenProviderAdapter(CustomTokenProviderAdaptee adaptee, int customTokenFetchRetryCount) {\n     Preconditions.checkNotNull(adaptee, \"adaptee\");\n     this.adaptee = adaptee;\n+    fetchTokenRetryCount = customTokenFetchRetryCount;\n   }\n \n   protected AzureADToken refreshToken() throws IOException {\n     LOG.debug(\"AADToken: refreshing custom based token\");\n \n     AzureADToken azureADToken = new AzureADToken();\n-    azureADToken.setAccessToken(adaptee.getAccessToken());\n+\n+    String accessToken = null;\n+\n+    Exception ex;\n+    boolean succeeded = false;\n+    // Custom token providers should have their own retry policies,\n+    // Providing a linear retry option for the the retry count\n+    // mentioned in config \"fs.azure.custom.token.fetch.retry.count\"\n+    int retryCount = fetchTokenRetryCount;\n+    do {\n+      ex = null;\n+      try {\n+        accessToken = adaptee.getAccessToken();\n+        LOG.trace(\"CustomTokenProvider Access token fetch was successful with retry count {}\", retryCount);", "originalCommit": "57bb403440aa9a4638a887c904f099709bc4ae9b", "replyToReviewId": null, "replies": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMjUxODE4Nw==", "url": "https://github.com/apache/hadoop/pull/1923#discussion_r412518187", "bodyText": "Retaining the trace log as we have had couple of debugging scenarios where customTokenProvider implementation hung on execution. Trace log right after the adapter.getAccessToken() will provide quick indication of the issue.\nFrom previous PRs, have confirmation from Steve too that its not costly.\n#1842 (comment)\nHave fixed the wrong retry count getting displayed in log.", "author": "snvijaya", "createdAt": "2020-04-21T21:54:26Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQwNTI4OTgwOA=="}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMjY2MjY3NQ==", "url": "https://github.com/apache/hadoop/pull/1923#discussion_r412662675", "bodyText": "I see, this is not string concatenation.", "author": "DadanielZ", "createdAt": "2020-04-22T04:34:50Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQwNTI4OTgwOA=="}], "type": "inlineReview", "revised_code": {"commit": "716c8d80c7553da95efd277a2bf5341a6d83de26", "chunk": "diff --git a/hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/oauth2/CustomTokenProviderAdapter.java b/hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/oauth2/CustomTokenProviderAdapter.java\nindex 7989080f1f8..6f2ca0d5586 100644\n--- a/hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/oauth2/CustomTokenProviderAdapter.java\n+++ b/hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/oauth2/CustomTokenProviderAdapter.java\n\n@@ -71,9 +71,11 @@ protected AzureADToken refreshToken() throws IOException {\n       ex = null;\n       try {\n         accessToken = adaptee.getAccessToken();\n-        LOG.trace(\"CustomTokenProvider Access token fetch was successful with retry count {}\", retryCount);\n+        LOG.trace(\"CustomTokenProvider Access token fetch was successful with retry count {}\",\n+            (fetchTokenRetryCount - retryCount));\n       } catch (Exception e) {\n-        LOG.debug(\"CustomTokenProvider Access token fetch failed with retry count {}\", retryCount);\n+        LOG.debug(\"CustomTokenProvider Access token fetch failed with retry count {}\",\n+            (fetchTokenRetryCount - retryCount));\n         ex = e;\n       }\n \n"}}, {"oid": "716c8d80c7553da95efd277a2bf5341a6d83de26", "url": "https://github.com/apache/hadoop/commit/716c8d80c7553da95efd277a2bf5341a6d83de26", "message": "Fix the retry count printed in the log", "committedDate": "2020-04-21T18:21:51Z", "type": "commit"}, {"oid": "2515f7d169b86a17eacb0c83cf44387e97771179", "url": "https://github.com/apache/hadoop/commit/2515f7d169b86a17eacb0c83cf44387e97771179", "message": "Javadoc fix for max retry count param", "committedDate": "2020-04-21T21:47:24Z", "type": "commit"}]}