{"pr_number": 2036, "pr_title": "HADOOP-17052. NetUtils.connect() throws unchecked exception (UnresolvedAddressException) causing clients to abort", "pr_createdAt": "2020-05-27T23:42:23Z", "pr_url": "https://github.com/apache/hadoop/pull/2036", "timeline": [{"oid": "fe90916e8127afb2662f1b8be99006b800c0dcef", "url": "https://github.com/apache/hadoop/commit/fe90916e8127afb2662f1b8be99006b800c0dcef", "message": "HADOOP-17052: Throw UnknownHostException in NetUtils.connect", "committedDate": "2020-05-27T23:33:56Z", "type": "commit"}, {"oid": "07c6c2a9978ada5bbfb127b98a251054eb50ea9b", "url": "https://github.com/apache/hadoop/commit/07c6c2a9978ada5bbfb127b98a251054eb50ea9b", "message": "Merge branch 'trunk' into HADOOP-17052", "committedDate": "2020-05-27T23:39:08Z", "type": "commit"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQzMjMwODgzMw==", "url": "https://github.com/apache/hadoop/pull/2036#discussion_r432308833", "bodyText": "nit: I know this is following existing test case, but since we now have a logger, we can use this:\nLOG.info(\"Got expected exception\", uhe);\n\nSytem.err in test code is not friendly to test output/log interpretation.", "author": "liuml07", "createdAt": "2020-05-29T07:39:32Z", "path": "hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/net/TestNetUtils.java", "diffHunk": "@@ -95,7 +95,25 @@ public void testAvoidLoopbackTcpSockets() throws Throwable {\n       assertInException(se, \"Invalid argument\");\n     }\n   }\n-  \n+\n+  @Test\n+  public void testInvalidAddress() throws Throwable {\n+    Configuration conf = new Configuration();\n+\n+    Socket socket = NetUtils.getDefaultSocketFactory(conf)\n+        .createSocket();\n+    socket.bind(new InetSocketAddress(\"127.0.0.1\", 0));\n+    try {\n+      NetUtils.connect(socket,\n+          new InetSocketAddress(\"invalid-test-host\",\n+              0), 20000);\n+      socket.close();\n+      fail(\"Should not have connected\");\n+    } catch (UnknownHostException ce) {\n+      System.err.println(\"Got exception: \" + ce);", "originalCommit": "07c6c2a9978ada5bbfb127b98a251054eb50ea9b", "replyToReviewId": null, "replies": null, "type": "inlineReview"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQzMjMyNzgzNA==", "url": "https://github.com/apache/hadoop/pull/2036#discussion_r432327834", "bodyText": "nit: call it uae?", "author": "liuml07", "createdAt": "2020-05-29T08:17:12Z", "path": "hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/net/NetUtils.java", "diffHunk": "@@ -534,6 +535,8 @@ public static void connect(Socket socket,\n       }\n     } catch (SocketTimeoutException ste) {\n       throw new ConnectTimeoutException(ste.getMessage());\n+    }  catch (UnresolvedAddressException ue) {", "originalCommit": "07c6c2a9978ada5bbfb127b98a251054eb50ea9b", "replyToReviewId": null, "replies": null, "type": "inlineReview"}, {"oid": "8bc3e656db272d08379fd4b8517842b7f76c8945", "url": "https://github.com/apache/hadoop/commit/8bc3e656db272d08379fd4b8517842b7f76c8945", "message": "Address code review comments", "committedDate": "2020-05-30T21:30:40Z", "type": "commit"}]}